Repository hjaremko/cute-animals, pull requests merged in 2020-06, with the labels that each got.

#74 Implement equipping and discarding items
  src/main/java/pl/uj/io/cuteanimals/model/ArmorBackpack.java
  src/main/java/pl/uj/io/cuteanimals/model/EquipItem.java
  src/main/java/pl/uj/io/cuteanimals/model/Item.java
  src/main/java/pl/uj/io/cuteanimals/model/ItemType.java
  src/main/java/pl/uj/io/cuteanimals/model/ThrowAwayAction.java
  src/main/java/pl/uj/io/cuteanimals/model/UnequipItem.java
  src/main/java/pl/uj/io/cuteanimals/model/WorldMap.java
  src/main/java/pl/uj/io/cuteanimals/model/action/PickupAction.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/IItem.java
  src/main/java/pl/uj/io/cuteanimals/model/interpreter/Interpreter.java
  src/main/resources/templates/index.html
Labels: enhancement, server

#86 Interpreter switch
  src/main/java/pl/uj/io/cuteanimals/controller/GameController.java
  src/main/java/pl/uj/io/cuteanimals/model/interpreter/Interpreter.java
  src/main/java/pl/uj/io/cuteanimals/service/GameService.java
  src/test/java/pl/uj/io/cuteanimals/model/InterpreterTest.java
Labels: enhancement

#87 Add prod and dev environment
  Dockerfile
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: process improvement

#101 Resolve some problems reported by PMD (#88)
  src/main/java/pl/uj/io/cuteanimals/controller/GameController.java
  src/main/java/pl/uj/io/cuteanimals/model/ArmorBackpack.java
  src/main/java/pl/uj/io/cuteanimals/model/Backpack.java
  src/main/java/pl/uj/io/cuteanimals/model/Castle.java
  src/main/java/pl/uj/io/cuteanimals/model/ChamberOfWealth.java
  src/main/java/pl/uj/io/cuteanimals/model/DevastatedLands.java
  src/main/java/pl/uj/io/cuteanimals/model/Dungeon.java
  src/main/java/pl/uj/io/cuteanimals/model/DungeonEgress.java
  src/main/java/pl/uj/io/cuteanimals/model/DungeonEntrance.java
  src/main/java/pl/uj/io/cuteanimals/model/Forest.java
  src/main/java/pl/uj/io/cuteanimals/model/ForestGlade.java
  src/main/java/pl/uj/io/cuteanimals/model/Inn.java
  src/main/java/pl/uj/io/cuteanimals/model/Medical.java
  src/main/java/pl/uj/io/cuteanimals/model/Moat.java
  src/main/java/pl/uj/io/cuteanimals/model/NPC.java
  src/main/java/pl/uj/io/cuteanimals/model/Player.java
  src/main/java/pl/uj/io/cuteanimals/model/PlayerAttributes.java
  src/main/java/pl/uj/io/cuteanimals/model/PlayerBackpack.java
  src/main/java/pl/uj/io/cuteanimals/model/ShamanCabin.java
  src/main/java/pl/uj/io/cuteanimals/model/Stable.java
  src/main/java/pl/uj/io/cuteanimals/model/Supervillain.java
  src/main/java/pl/uj/io/cuteanimals/model/Town.java
  src/main/java/pl/uj/io/cuteanimals/model/Trap.java
  src/main/java/pl/uj/io/cuteanimals/model/Village.java
  src/main/java/pl/uj/io/cuteanimals/model/WorldMap.java
  src/main/java/pl/uj/io/cuteanimals/model/action/DungeonEntranceGoAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/DungeonInvestigateAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/EquipItem.java
  src/main/java/pl/uj/io/cuteanimals/model/action/GoAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/InvestigateAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/MessageAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/PickupAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/ShowArmor.java
  src/main/java/pl/uj/io/cuteanimals/model/action/ShowBackpack.java
  src/main/java/pl/uj/io/cuteanimals/model/action/ShowStats.java
  src/main/java/pl/uj/io/cuteanimals/model/action/TalkAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/ThrowAwayAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/UnequipItem.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/ArgumentAction.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/ArgumentlessAction.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/ILocation.java
  src/main/java/pl/uj/io/cuteanimals/model/interpreter/Interpreter.java
  src/main/java/pl/uj/io/cuteanimals/service/AttributesService.java
  src/main/java/pl/uj/io/cuteanimals/service/GameService.java
Labels: bug, enhancement

#104 Chating implementation.
  src/main/java/pl/uj/io/cuteanimals/model/WorldMap.java
  src/main/java/pl/uj/io/cuteanimals/plot/locations/MedicalCabin.java
Labels: story

#107 Picking up items implementation.
  src/main/java/pl/uj/io/cuteanimals/model/WorldMap.java
  src/main/java/pl/uj/io/cuteanimals/service/AttributesService.java
  src/main/java/pl/uj/io/cuteanimals/service/ItemService.java
Labels: story

#108 Implement nice backpacking printing
  src/main/java/pl/uj/io/cuteanimals/model/Backpack.java
Labels: client, enhancement

#117 Reduce duplicate code in Action class family
  src/main/java/pl/uj/io/cuteanimals/action/EquipItem.java
  src/main/java/pl/uj/io/cuteanimals/action/GoAction.java
  src/main/java/pl/uj/io/cuteanimals/action/InvestigateAction.java
  src/main/java/pl/uj/io/cuteanimals/action/MessageAction.java
  src/main/java/pl/uj/io/cuteanimals/action/PickupAction.java
  src/main/java/pl/uj/io/cuteanimals/action/ShowArmor.java
  src/main/java/pl/uj/io/cuteanimals/action/ShowBackpack.java
  src/main/java/pl/uj/io/cuteanimals/action/ShowStats.java
  src/main/java/pl/uj/io/cuteanimals/action/TalkAction.java
  src/main/java/pl/uj/io/cuteanimals/action/ThrowAwayAction.java
  src/main/java/pl/uj/io/cuteanimals/action/UnequipItem.java
  src/main/java/pl/uj/io/cuteanimals/model/Player.java
  src/main/java/pl/uj/io/cuteanimals/model/WorldMap.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/ArgumentAction.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/ArgumentlessAction.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/ContainerArgumentAction.java
  src/main/java/pl/uj/io/cuteanimals/plot/actions/DungeonEntranceGoAction.java
  src/main/java/pl/uj/io/cuteanimals/plot/actions/DungeonInvestigateAction.java
  src/test/java/pl/uj/io/cuteanimals/interpreter/InterpreterTest.java
Labels: enhancement

#123 Fix crash after supplying args to argumentless commands (#120)
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/ArgumentlessAction.java
Labels: bug

#122 Overhaul client terminal
  src/main/resources/static/style.css
  src/main/resources/templates/index.html
Labels: client, enhancement

#124 Changes in investigate description.
  src/main/java/pl/uj/io/cuteanimals/model/WorldMap.java
  src/main/java/pl/uj/io/cuteanimals/service/AttributesService.java
  src/main/java/pl/uj/io/cuteanimals/service/GameService.java
  src/main/java/pl/uj/io/cuteanimals/service/ItemService.java
Labels: bug, story

#127 Add missing trap action
  src/main/java/pl/uj/io/cuteanimals/model/WorldMap.java
Labels: bug

#132 Fix version reported by client
  src/main/resources/templates/index.html
Labels: bug

#135 Apply review suggestions
  src/main/java/pl/uj/io/cuteanimals/model/Player.java
  src/main/resources/templates/index.html
Labels: enhancement

#138 Add endgame and fight action to locations.
  src/main/java/pl/uj/io/cuteanimals/model/WorldMap.java
  src/main/java/pl/uj/io/cuteanimals/model/fight/FightManager.java
Labels: server, story

#150 Fix experience being not calculated correctly (#142)
  src/main/java/pl/uj/io/cuteanimals/action/ability/Focus.java
  src/main/java/pl/uj/io/cuteanimals/model/fight/FightManager.java
  src/test/java/pl/uj/io/cuteanimals/action/ability/FocusTest.java
  src/test/java/pl/uj/io/cuteanimals/model/fight/FightManagerTest.java
Labels: bug

#152 Fix unstable test
  src/main/java/pl/uj/io/cuteanimals/model/Player.java
  src/main/java/pl/uj/io/cuteanimals/model/PlayerAttributes.java
  src/main/java/pl/uj/io/cuteanimals/model/RandomIntegerImpl.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/RandomInteger.java
  src/test/java/pl/uj/io/cuteanimals/action/ability/FocusTest.java
  src/test/java/pl/uj/io/cuteanimals/model/PlayerAttributesTest.java
Labels: bug

#151 Add command to print player's abilities (#131)
  src/main/java/pl/uj/io/cuteanimals/action/ShowAbilities.java
  src/main/java/pl/uj/io/cuteanimals/action/ability/Focus.java
  src/main/java/pl/uj/io/cuteanimals/action/ability/IAbility.java
  src/main/java/pl/uj/io/cuteanimals/location/LocationBuilder.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/IAbility.java
  src/main/resources/templates/index.html
Labels: enhancement

#168 Add uml
  README.md
  assets/CuteAnimals.svg
  assets/CuteAnimals.uml
  assets/CuteAnimalsActions.svg
  assets/CuteAnimalsCharacters.svg
  assets/CuteAnimalsEntities.svg
  assets/CuteAnimalsGameLogic.svg
  assets/CuteAnimalsInterpreter.svg
  assets/CuteAnimalsMisc.svg
  assets/CuteAnimalsRepositories.svg
  assets/UML.md
Labels: documentation
