Repository hjaremko/cute-animals, pull requests merged in 2020-05, with the labels that each got.

#43 Add project description to README
  README.md
Labels: documentation, enhancement

#47 Implement basic client
  src/main/java/pl/uj/io/cuteanimals/HelloController.java
  src/main/java/pl/uj/io/cuteanimals/controller/GameController.java
  src/main/resources/static/index.html
Labels: enhancement

#49 Publish PMD and SpotBugs reports (#40)
  .github/workflows/gradle.yml
Labels: documentation, enhancement

#48 Fix interpreter not throwing when given odd repeats of action command
  src/main/java/pl/uj/io/cuteanimals/model/interpreter/Interpreter.java
  src/test/java/pl/uj/io/cuteanimals/model/InterpreterTest.java
Labels: bug

#51 Add some missing javadoc strings, generate and upload documentation
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/pl/uj/io/cuteanimals/model/action/GoAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/InvestigateAction.java
  src/main/java/pl/uj/io/cuteanimals/model/action/MessageAction.java
  src/main/java/pl/uj/io/cuteanimals/model/interfaces/IAction.java
  src/main/java/pl/uj/io/cuteanimals/model/interpreter/Expression.java
Labels: documentation

#52 Improve web client
  build.gradle
  src/main/resources/static/style.css
  src/main/resources/templates/index.html
Labels: enhancement

#56 Design database
  src/main/java/pl/uj/io/cuteanimals/model/Item.java
Labels: enhancement
